// Auto-Generated by FAKE; do not edit
// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyVersion("0.0.1")]
[assembly: AssemblyFileVersion("0.0.1")]
[assembly: AssemblyInformationalVersion("0.0.1")]
[assembly: AssemblyCompany("Albelli")]
[assembly: AssemblyCopyright("Albelli")]
[assembly: ComVisible(false)]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyVersion = "0.0.1";
        internal const System.String AssemblyFileVersion = "0.0.1";
        internal const System.String AssemblyInformationalVersion = "0.0.1";
        internal const System.String AssemblyCompany = "Albelli";
        internal const System.String AssemblyCopyright = "Albelli";
        internal const System.Boolean ComVisible = false;
    }
}
