// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyVersionAttribute("0.1.0")]
[assembly: AssemblyFileVersionAttribute("0.1.0")]
[assembly: AssemblyInformationalVersionAttribute("0.1.0")]
[assembly: AssemblyCompanyAttribute("Albelli")]
[assembly: AssemblyCopyrightAttribute("Albelli")]
[assembly: ComVisibleAttribute(false)]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyVersion = "0.1.0";
        internal const System.String AssemblyFileVersion = "0.1.0";
        internal const System.String AssemblyInformationalVersion = "0.1.0";
        internal const System.String AssemblyCompany = "Albelli";
        internal const System.String AssemblyCopyright = "Albelli";
        internal const System.Boolean ComVisible = false;
    }
}
